package ru.job4j.devops;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main class
 * Default constructor generated by Lombok
 */
@SpringBootApplication
public class CalcApplication {

	/**
	 * Main method
	 * @param args command line args
	 */
	public static void main(String[] args) {
		SpringApplication.run(CalcApplication.class, args);
	}
}
